#!/bin/python

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jestex"
version = "0.8.0"
authors = [
  { name="Hugo Banderier", email="hugo.banderier@unibe.ch" },
]
description = "JEt STream and EXtreme events analysis"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hbanderi/jestex"
"Bug Tracker" = "https://github.com/hbanderi/jestex/issues"

