#!/bin/python

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jetstream_hugo"
version = "0.8.0"
authors = [
  { name="Hugo Banderier", email="hugo.banderier@unibe.ch" },
]
description = "Jet stream related functions and classes for my research"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hbanderi/jetstream_hugo"
"Bug Tracker" = "https://github.com/hbanderi/jetstream_hugo/issues"

